name: demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v.4.5
      - name: Maven打包中... LODING...
        run: |
          mvn clean
          mvn install -Dmaven.test.skip=true
      - name: Cat 文件中...
        run: ls
 
