name: demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v.4.5
      - name: Maven打包中... LODING...
        run: |
          mvn clean
          mvn install -Dmaven.test.skip=true
      - name: 构造镜像文件准备中... LOADING...
        run: |
          mv target/*.jar docker/APP.jar
      #- name: Docker 镜像构造上传中... LOADING...
        #run: |
          #docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ccr.ccs.tencentyun.com
          #cd docker
          #使用Dockerfile构建镜像
          #docker build --tag ccr.ccs.tencentyun.com/haos/demo:v1 .
          #推送镜像到镜像仓库
          #docker push ccr.ccs.tencentyun.com/haos/demo:v1
      - name: 登陆远程服务器... LOADING...
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a;pwd;docker -v
          host: haos.fun
          username: root
          port: 22
          password: ${{ secrets.ROOT_PASSWORD}}
      - name: Cat 文件中...
        run: ls
 
