name: demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Maven打包中... LODING...
        uses: stCarolas/setup-maven@v.4.5
      - name: 检查检查
        run: |
          mvn clean
          mvn install
      - name: 再检查检查
        run: ls
 
