name: demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v.4.5
      - name: Maven打包中... LODING...
        run: |
          mvn clean
          mvn install -Dmaven.test.skip=true
      - name: 构造镜像文件准备走... LOADING...
        run: |
          mv target/*.jar docker/APP.jar
          cd docker
          ls
      - name: Docker 镜像构造上传中... LOADING...
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ispeakcode/docker-githubaction
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Cat 文件中...
        run: ls
 
