name: demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maven打包中... LODING...
        uses: stCarolas/setup-maven@v.4.5
      - name: 检查检查
        run: |
          pwd
          mvn -v
      - name: 再检查检查
        run: ls
 
