name: docs

on:
  # 手动触发部署
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 登陆远程服务器... LOADING... 重新部署中...
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ll;docker stop app;docker rm app;docker pull ccr.ccs.tencentyun.com/haos/demo:v1;docker run -d -p 15006:8080 --name app ccr.ccs.tencentyun.com/haos/demo:v1
        host: haos.fun
        username: root
        port: 22
        password: ${{ secrets.ROOT_PASSWORD}}
